angular.module('app', [
    'ngRoute',
    'ngResource',
    'ui.router',
    'restangular',
    'ngSanitize',
    'app.constant',
    'app.front',
    'app.search',
    'templates-app'])

    .config(function ($stateProvider, $urlRouterProvider, RestangularProvider) {
        $urlRouterProvider.otherwise('/');
        RestangularProvider.setBaseUrl('/api/v1');
    })

    .controller('AppController', function($scope, $routeParams) {


    })


    .value('wordList', [
	"¡me lleva la chingada!",
	"¡me lleva la que me trajo!",
	"¿no quieres tu agüita de limón?",
	"¿qué onda?",
	"¿qué pasión?",
	"¿que pex?",
	"¿qué rollo?",
	"a golpe de calcetín",
	"a grito pelado",
	"a la brava",
	"a la chingada",
	"a lo macho",
	"a medios chiles",
	"a morir",
	"mandar  a la goma",
	"a patin",
	"a raiz",
	"a toda madre",
	"a todo dar",
	"a wilfur o a wiwis",
	"abarrotero",
	"abarrotes",
	"abrir cancha",
	"abrirse",
	"abuelita de Batman",
	"abusadillo",
	"abusado",
	"acabado",
	"acartonado",
	"acetato",
	"achaparrarse",
	"achatado",
	"achechar",
	"achicalada",
	"achicalado",
	"achicalar",
	"achicharrado",
	"achicharrar",
	"achicharronado",
	"achicharronar",
	"achicharronarse",
	"achicopalado",
	"achicopalarse",
	"achiote",
	"achipilarse",
	"acochambrado",
	"acochambrar",
	"acordeón",
	"acostadote",
	"acurrucado",
	"adelita",
	"adeveras",
	"adobera",
	"aeromoza",
	"afanador",
	"afuerita",
	"agarrado",
	"agarrar de barco",
	"agarrar de cochinito",
	"agarrar en curva",
	"agarrar la onda",
	"agarrón",
	"agringarse",
	"agripado",
	"agriparse",
	"agrura",
	"agruras",
	"agua de chía",
	"agua de jamaica",
	"aguacate",
	"aguantame tantito",
	"aguas frescas",
	"ah, jijo!",
	"ahí muere",
	"ahí nomás",
	"Ahí nos vicenteamos",
	"ahí nos vidrios",
	"ahijado",
	"ahogado",
	"aironazo",
	"ajolote",
	"ajuariado",
	"ajuariar",
	"al ahi se va",
	"al aventón",
	"ponerse al brinco",
	"al chas chas",
	"al chile",
	"al cuas",
	"al pelo",
	"al que le venga el saco, que se lo ponga",
	"al tiro",
	"alambre",
	"alardeo",
	"albañil",
	"alberca",
	"Albitro",
	"albur",
	"albur",
	"albureador",
	"alburear",
	"alburero",
	"alebrestado",
	"alebrestar",
	"alebrestarse",
	"alebrije",
	"alhajero",
	"alhajita",
	"alivianar",
	"alivianarse",
	"aliviarse",
	"allacito",
	"almuerzo",
	"altote",
	"amá",
	"amacharse",
	"amarchantarse",
	"amarrado",
	"amarrar, amarrarse",
	"ambrosía",
	"amelcocharse",
	"amiguero",
	"amolada",
	"amolado",
	"amoladón",
	"amolar",
	"amolarse",
	"ampolleta",
	"andadera",
	"andador",
	"ándale",
	"ándale pues",
	"andar alguien hasta el gorro",
	"andar como burro sin mecate",
	"andar con el cutis flojo",
	"andar de pirujo",
	"andar en la bola",
	"andar pedo",
	"andar tomado",
	"andar tras los huesos de alguien",
	"angina",
	"ansia",
	"antojitos",
	"antojo",
	"apá",
	"apá",
	"apache",
	"apachurrado",
	"apachurramiento",
	"apachurrar",
	"apachurrón",
	"apagador",
	"apañar",
	"apantallado",
	"apantallar",
	"apapachar",
	"apapacho",
	"apenado",
	"apenarse",
	"apendejado",
	"apendejarse",
	"apenitas",
	"aperingar",
	"aplatanado",
	"apochado",
	"apocharse",
	"apretado",
	"apretarse",
	"apuntarse",
	"araña",
	"archivero",
	"arderse",
	"ardido",
	"ardilla voladora",
	"argolla",
	"argüende",
	"argüendear",
	"argüendero",
	"armar bronca",
	"armarla",
	"arrachera",
	"arrastrado",
	"arrastrar la cobija",
	"arrejuntado",
	"arrejuntarse",
	"arroz con leche",
	"asadera",
	"asistonto",
	"atizar mota",
	"atocigar",
	"atole",
	"atorarse",
	"atorón",
	"atrabancado",
	"atracar",
	"aumento",
	"aventado",
	"aventado",
	"aventarse",
	"aventón",
	"aviador",
	"avorazado",
	"avorazarse",
	"azagata",
	"azonzado",
	"azonzarse",
	"azorrillado",
	"azotar",
	"azotarse",
	"azotón",
	"azteca",
	"azul",
	"babosada",
	"babosear",
	"baboso",
	"bacha",
	"bacinica",
	"baika",
	"Bailongo",
	"bajar",
	"balacear",
	"balata",
	"balazo",
	"balero",
	"ballena",
	"bamba",
	"bañársela",
	"banda",
	"banderazo",
	"baño ruso, o baño turco",
	"baquetón",
	"barajearla más despacio",
	"barata",
	"baratero",
	"barbero",
	"baro",
	"barrer",
	"basculiar",
	"basquet",
	"bataca",
	"batallar",
	"batidillo",
	"bato",
	"beba",
	"bemba",
	"bembudo",
	"bestia",
	"betabel",
	"bichi",
	"bici",
	"bicla",
	"bien bien",
	"bien mal",
	"bigotes de aguacero",
	"birote",
	"birria",
	"bisbirindo o bizbirindo",
	"biznaga",
	"blanquillo",
	"bobierno",
	"bobo",
	"bodega",
	"bodoque",
	"bodorrio",
	"bofeado",
	"bofo",
	"bóiler",
	"Boinas pa los calvos",
	"bola",
	"bola de",
	"boleada",
	"bolear",
	"bolero",
	"boleta",
	"bolillo",
	"bollo",
	"bolo",
	"bolsa",
	"bolseada",
	"bolseador",
	"bolsear",
	"boludo",
	"bombo",
	"bonche",
	"borlote",
	"borracho",
	"botadero",
	"botana",
	"botanear",
	"bote",
	"botellón",
	"botijón",
	"brasero",
	"brasier",
	"Briago",
	"brincacharcos",
	"brincos dieras",
	"bronca",
	"bronco",
	"buchón",
	"buena onda",
	"buenazo",
	"bueno/buenón/buenote",
	"buey",
	"buey o güey",
	"buki, buqui",
	"buró",
	"burra",
	"burrito",
	"burro",
	"buscapleitos",
	"buzo",
	"caballo",
	"cabeza de cerillo",
	"cabrito",
	"cabrón (estar)",
	"cabrón (ser)",
	"cacahuate",
	"cachar",
	"cacharpa",
	"cachete",
	"cachetear",
	"cachetear banquetas",
	"cachetiza",
	"cachetón",
	"cachirul",
	"cachondear",
	"cachondo",
	"cacle",
	"caer de a madre",
	"caer el veinte",
	"caer gordo",
	"caerse los chones",
	"cagar",
	"cagar el palo",
	"cagarse",
	"caguama",
	"cajearse",
	"cajeta",
	"calabaza",
	"calabesear",
	"calaca",
	"caliente",
	"Calmantes montes",
	"calo",
	"calote",
	"calzonear",
	"calzones",
	"camara",
	"Cámara de gas",
	"Cambio de agua a las aceitunas",
	"caminar",
	"camion",
	"camotes",
	"campechano",
	"campeona de natación",
	"canijo",
	"cantar mal las rancheras",
	"cantón",
	"capear",
	"capirucha",
	"carabina",
	"carcacha",
	"caricaturas",
	"carita",
	"carnal",
	"carrilla",
	"carrilludo",
	"carriola",
	"carro",
	"cascabelear",
	"cascarear",
	"cascarita",
	"cateado",
	"catego",
	"catrín",
	"cenote",
	"centenario",
	"cercas",
	"cerote",
	"Cha!! no Maa...!!",
	"chaca chaca",
	"chachalaca",
	"cháchara",
	"chacharear",
	"chacharero",
	"chacualear",
	"chafa",
	"chafear",
	"chafirete",
	"chalán",
	"chale",
	"chamaco",
	"chamacona",
	"chamagoso",
	"chamarra",
	"chamba",
	"chambeador",
	"chambear",
	"chambelán",
	"chambón",
	"chambrita",
	"chamorro",
	"champurrado",
	"chamuco",
	"chance",
	"chancho",
	"chancla",
	"chanclear",
	"changa (estar)(ser)",
	"changarro",
	"chango",
	"chante",
	"chao",
	"chaparro",
	"chapeado",
	"chaperón",
	"chapucero",
	"chaquetear",
	"chaquetón",
	"charola",
	"charra",
	"charro",
	"chato",
	"chavo",
	"checar",
	"chela",
	"Chela, birrias, heladas, ambarinas=Cerveza",
	"chelo",
	"chemo",
	"chero",
	"cheve",
	"chévere",
	"chicano",
	"chícharo",
	"chicharrón",
	"Chicharrones, gomas, teclas",
	"chiche o chichi",
	"chichi",
	"chichifo",
	"chicho",
	"chicle",
	"chido",
	"chiflado",
	"chilango",
	"Chilangolandia",
	"chilapastroso",
	"chilaquiles",
	"chillar",
	"chilletas",
	"chilo",
	"chilpayate",
	"chilpayate",
	"chimuelo",
	"chin!",
	"chinga",
	"chinga a tu madre!",
	"chingada",
	"chingadazo",
	"chingadera",
	"chingaderita",
	"chingado",
	"chíngale!/¡chínguele!/¡chínguenle!",
	"chingao!",
	"chingaquedito",
	"chingar",
	"chingar",
	"chingatal",
	"chingo",
	"chingo",
	"chingón",
	"chingón (ser)(estar)",
	"chipichipi",
	"chipocludo",
	"chiqueado",
	"chiquear",
	"chiqueón",
	"chiripada",
	"chismorrear",
	"chismoso",
	"chispotear (algo)",
	"chiva",
	"chivas",
	"chivas",
	"chiveado",
	"chivearse",
	"chivearse",
	"chocho",
	"choco",
	"choco",
	"chocoso",
	"cholo",
	"Chompeta, Chompa, La Terraza, Mema",
	"chómpiras",
	"choncho",
	"chones",
	"chongo",
	"chorillo",
	"choro",
	"choro",
	"chorro",
	"chorronal",
	"chorroscientos",
	"chota",
	"Chota, placa, pitufos, ley",
	"choteado",
	"choteado",
	"chotear",
	"choya",
	"chucherias",
	"chueco",
	"chufa",
	"chulear",
	"chulear",
	"chulo",
	"chulo",
	"chundo",
	"chuntara",
	"chupar",
	"chupe",
	"chupete",
	"churido",
	"churro",
	"churro",
	"Churro",
	"chutar",
	"ciego",
	"ciscar",
	"claridoso",
	"clarín",
	"clavado",
	"clavar",
	"clavarse",
	"clavarse",
	"coche",
	"coco",
	"codo",
	"codo",
	"codomontano",
	"coger",
	"cogida",
	"colación",
	"colado",
	"colgado",
	"colgar los tenis",
	"colmilludo",
	"colonia",
	"comadrear",
	"comal",
	"comelón",
	"comer como pelón de hospicio",
	"comer gordo",
	"como agua para chocolate",
	"como agua para chocolate",
	"como chingas!",
	"como el chile piquín: chiquito, pero picoso",
	"como friegas!",
	"como jefe",
	"como jodes!",
	"como la chingada",
	"como va",
	"compa",
	"compadre",
	"con el ojo cuadrado",
	"Concha",
	"conchudo",
	"conchudo",
	"congal",
	"cooperacha",
	"coperacha",
	"copiosa",
	"corcholata",
	"corriente",
	"córtalas",
	"cortar",
	"cortarse un huevo y la mitad del otro",
	"Cortarse un huevo y la mitad del otro",
	"coscorrón",
	"cosechar",
	"cotorrear",
	"cotorreo",
	"cotorreo",
	"coyote",
	"coyote",
	"coyotito",
	"cruda",
	"cruda",
	"crudo (estar)(andar)",
	"cuachalote",
	"cuaderno",
	"cuadrar",
	"cuando todos albañiles, ¿quién da mezcla?",
	"cuatache",
	"cuatacho",
	"cuate",
	"Cuate",
	"cuate",
	"cuatrapeado",
	"cuatrapear",
	"cuatrapear",
	"cubeta",
	"cubetada",
	"cubetazo",
	"cucharón",
	"cuentear",
	"cuerazo",
	"cuerno de chivo",
	"cuero (ser un)(estar)",
	"cuerpazo",
	"cuete",
	"culero",
	"cura",
	"curado (ser) (estar)",
	"dar aire (a alguien)",
	"dar atole con el dedo",
	"Dar el rol",
	"dar en la madre",
	"dar en la torre",
	"dar hueva",
	"dar lata",
	"dar pamba",
	"dar un aventón",
	"dar un quemón",
	"dar una mordida",
	"dar una paliza",
	"darle a alguien por su lado.",
	"darle a alguien un aire",
	"darle al clavo",
	"darse color",
	"darse paquete/darse mucho taco",
	"darse un (ligero) quemón",
	"darse un agarrón",
	"darse una matada",
	"dárselas de",
	"dárselas de muy muy",
	"de a grapa",
	"de cajón",
	"de gorra (como en entrar de gorra)",
	"de hueso colorado",
	"de hueso colorado",
	"de la chingada",
	"de la patada",
	"de la patada",
	"de pelos/peluches",
	"de peluche",
	"de perdida",
	"de perdida",
	"de perdis",
	"de sangre pesada",
	"de volada",
	"dedazo",
	"dedo",
	"dejar abajo",
	"dejar como novia de rancho",
	"dejar como palo de gallinero",
	"dejar de a seis",
	"dejar plantado",
	"del año de la canica",
	"del año del caldo",
	"del cocol",
	"del nabo",
	"del otro bando",
	"desafanarse",
	"desarmador",
	"desbalagado",
	"descalabrarse",
	"descarado",
	"deschavetar",
	"descolgarse",
	"desconchabado o desconchavado",
	"desconchabar",
	"desconchinflado",
	"desconchinflar",
	"desconchinflar",
	"descontarse",
	"descuachalangado",
	"desmadrar",
	"desmadre",
	"desmadre",
	"desnarizarse",
	"despacharse",
	"despapaye",
	"despapaye",
	"despedorrar",
	"desquintar",
	"destanteado",
	"destartalado",
	"destartalado",
	"deste",
	"destrampe",
	"diablito",
	"Diente de ballena",
	"Diferiencia",
	"disparar",
	"doña blanca",
	"donde hubo fuego, cenizas quedan",
	"dos-tres",
	"echale ganas!",
	"echando a perder se aprende",
	"echar aguas",
	"echar aguas",
	"echar bronca",
	"echar de cabeza",
	"echar el ojo",
	"echar los perros",
	"echar madres",
	"echar mucha crema a los tacos",
	"echar papa",
	"echar porras",
	"echar un fonazo",
	"echar una firma",
	"echarle a alguien un grito",
	"echarle ganas",
	"echarle mucha crema a sus tacos",
	"echarse a alguien (al plato)",
	"echarse para atrás",
	"echarse un pedo",
	"echarse un taco",
	"école!",
	"edad de la punzada",
	"efectivo",
	"el burro por delante",
	"el otro lado",
	"el que da y quita, con el diablo se desquita",
	"el que es perico, dondequiera es verde",
	"elevador",
	"elotero",
	"embarcarse",
	"embicharse",
	"empachada",
	"empedarse",
	"empinado",
	"en bola",
	"en chinga",
	"en fa",
	"en caliente",
	"en fachas",
	"en friega",
	"en la torre!",
	"en menos de lo que canta un gallo",
	"en pelotas",
	"en puros cueros",
	"encabronar",
	"encabronarse",
	"encajoso",
	"encanijado",
	"encarrilar",
	"enchamarrado",
	"enchilado",
	"Enchilarse",
	"enchinar el cuero",
	"enchufar",
	"encimoso",
	"encuerado",
	"endrogado",
	"enmuinarse",
	"enseñar hasta el apellido",
	"enseñar hasta las anginas",
	"enserio",
	"entós qué, loco?",
	"entrado",
	"entre menos burros, más olotes",
	"Es bien largo ó logrón",
	"escamado",
	"escamar",
	"escuadra",
	"escuincle",
	"escuincle",
	"ése",
	"esquite",
	"estar  bien parado",
	"estar alguien en su mero mole",
	"estar cabrón",
	"estar Chafón",
	"estar como agua para chocolate",
	"estar con el niño atravesado",
	"estar curioso",
	"estar dado al cuas",
	"estar de antojo",
	"estar de poca",
	"estar mamey",
	"estar más puesto que un calcetín",
	"estar pa'l arrastre",
	"estar Papita",
	"estar parado de pestañas",
	"estar pedo",
	"estar podrido en dinero",
	"estar puesto",
	"estar/andar jullido",
	"fachadiento",
	"fachas",
	"fachoso",
	"fachoso",
	"fachudo",
	"Fajar",
	"fajarse",
	"faje",
	"falluca o fayuca",
	"falluquear o fayuquear",
	"farol",
	"farol",
	"farolazo",
	"fayuca",
	"fayuquero",
	"feliz como una lombriz",
	"felón",
	"feria",
	"feria",
	"fichera",
	"fierro",
	"fierro!",
	"fifar",
	"fijado",
	"filero",
	"flaca",
	"flete",
	"flojera",
	"flojo",
	"fodongo",
	"fraccionamiento",
	"fregada",
	"fregadazo",
	"fregadera",
	"fregado",
	"fregado",
	"fregar",
	"Fregar",
	"fregar",
	"fregón",
	"fregón",
	"frenos",
	"fresa",
	"fresa",
	"fría",
	"fría",
	"friega",
	"friega",
	"friego",
	"FUA",
	"fuchi",
	"fuego",
	"fufurufo",
	"fumar como un chacuaco",
	"fumigado",
	"fumigado",
	"fúrico",
	"fúrico",
	"furris",
	"fusca",
	"fusilar",
	"gabacho",
	"gabacho",
	"Gabacho",
	"gacho",
	"Gacho",
	"gacho",
	"galán",
	"gallo",
	"gana",
	"gancho",
	"gandalla",
	"gargajo.",
	"garigoleado",
	"garnacha",
	"gasof",
	"gata",
	"gaviota",
	"gaznate",
	"golfa",
	"gordinflas",
	"gorro",
	"Gorrón",
	"gota",
	"Greñas",
	"grifo",
	"grilla",
	"gringada",
	"Gringo",
	"gringo",
	"Gringolandia",
	"gripa",
	"groserías",
	"grueso",
	"guacal",
	"guácala!",
	"guacamole",
	"guacarear",
	"guachar",
	"guacho",
	"guaje",
	"guaje o huaje",
	"guajolote",
	"guamazo",
	"guamazo",
	"guandajón",
	"guango",
	"guango",
	"guapachoso",
	"guarache",
	"guardadito",
	"guarura",
	"guarura",
	"guasa",
	"guasanga",
	"guato",
	"güera",
	"güera",
	"güero",
	"güero",
	"güeva",
	"güevón",
	"güey o wey",
	"güila",
	"güilo",
	"güiri-güiri",
	"güirigüiri",
	"Hace Frijolito",
	"hacer chanchullo",
	"hacer changuitos",
	"hacer changuitos",
	"hacer chis",
	"hacer de chile los tamales",
	"hacer de chivo los tamales",
	"hacer del dos",
	"hacer del uno",
	"hacer del uno",
	"hacer jalón",
	"hacer la valona",
	"hacer los mandados",
	"hacer manita de cochi",
	"hacer panchos",
	"hacer talacha",
	"hacerla de jamon",
	"hacerla de tos",
	"hacerle a alguien agua la canoa",
	"hacerle a alguien una valona",
	"hacerle al loco",
	"hacerle el fuchi",
	"hacerse alguien bolas",
	"hacerse atole",
	"hacerse cachetón",
	"hacerse de la vista gorda",
	"hacerse la pinta",
	"hacerse pato",
	"hacerse uno loco",
	"Haiga",
	"Hartas",
	"hasta atrás",
	"hasta el gorro",
	"hasta la madre",
	"Haz Changuitos",
	"hecho la chingada",
	"hecho la mocha",
	"hielera",
	"hijole",
	"híjole",
	"hijos de papi",
	"hocicón",
	"hojaldra",
	"hornazo",
	"huacho",
	"huaje",
	"huarache o guarache",
	"huarachudo",
	"huerco",
	"huerco o güerco",
	"hueva",
	"hueva",
	"hueva o güeva",
	"Huevo",
	"huevón",
	"huevón",
	"huevonada",
	"idiotizado",
	"idiotizar",
	"ido",
	"igualado",
	"igualado",
	"Iguanas ranas",
	"importarle algo a alguien un cacahuate",
	"impuesto",
	"ingeniebrio",
	"ínguiasu!/¡ínguiesu!",
	"ir a cambiar el agua al canario",
	"ir a drenar al jefe",
	"ir a la chingada",
	"ir a liberar a Nelson Mandela",
	"ir a liberar a Willy",
	"ir a mandar un fax a las tortugas Ninja",
	"ir a sacar el topo a nadar",
	"ir a tirar el lodo",
	"ir como en feria",
	"irse algo a la chingada",
	"irse de pinta",
	"itacate",
	"jacal",
	"jacalear",
	"Jaina",
	"jala más un pelo de mujer que una yunta de bueyes",
	"Jalada",
	"jalada",
	"jalador",
	"jalar parejo",
	"jalas o te pandeas?",
	"jale",
	"jalisquillo",
	"jambado",
	"jambado",
	"jambarse",
	"jarabe de pico",
	"jarocho",
	"jefa",
	"jefe",
	"jetear",
	"jetón",
	"jimbar",
	"jinetear",
	"jinetear",
	"jodicial",
	"jodón",
	"joto",
	"joto",
	"julia",
	"junior",
	"junior",
	"la casa chica",
	"La Llorona",
	"Lady very well papas with betabel, i want to do the cuchupumplais with you",
	"lagartijas",
	"lambiscón",
	"lambiscón",
	"lambisconear",
	"lambisconería",
	"Lana",
	"lana",
	"lana",
	"Lana, Marmaja, Firula",
	"lanzar",
	"lapicero",
	"Las Narices",
	"latir",
	"latir",
	"lavar el coco",
	"le caemos o que?",
	"lépero",
	"Licaste huachaste",
	"lío",
	"lira",
	"lisa",
	"livais",
	"llanta",
	"llantas",
	"llevar pifas",
	"llevarla (ahi)",
	"lo mismo da Chana que Juana.",
	"loco",
	"locochón",
	"lonche",
	"lucas",
	"machaca",
	"machacado",
	"machetear",
	"machetear",
	"machetero",
	"machetero",
	"Machihui",
	"Machin",
	"machín",
	"machorra",
	"machucar",
	"maciza",
	"macuarro",
	"madrazo",
	"madrazo",
	"madrazo",
	"madrear",
	"madrear",
	"madrecita",
	"madriza",
	"mafufo",
	"mafufo",
	"maistro",
	"Maistro",
	"maje",
	"malafacha",
	"malandrín",
	"malilla",
	"malinchismo",
	"malinchista",
	"mamada",
	"Mamada",
	"mamada",
	"mamado",
	"mamado",
	"mamado",
	"mamado",
	"mamey",
	"mamón",
	"mañanitas",
	"manchado (ser)",
	"mancharse",
	"mandado",
	"mandilón",
	"mangazo",
	"mango",
	"mano",
	"mañoso",
	"mantado",
	"mariachi",
	"mariachi",
	"mariposilla",
	"mariposón",
	"mariquita",
	"mariquita",
	"marro",
	"más loco que una cabra",
	"más mexicano que el nopal",
	"Más mezcla maistro, o le remojo los adobes?",
	"Más mucho",
	"más pior",
	"matada",
	"mayate",
	"mayativo",
	"Me fui a patín rin",
	"me lleva el chanfle!",
	"Me salí pa fuera",
	"Me voy a cortar el pasto",
	"me voy a rebajar la melena",
	"me voy a trasquilar",
	"mecate",
	"Mechas",
	"mechudo",
	"meco",
	"Medirle el agua a los camotes",
	"méndigo",
	"menear el tambo",
	"mensada",
	"menso",
	"mentada",
	"mentar a la madre",
	"mentar la madre",
	"mentarle la madre a alguien",
	"menudo",
	"menzo",
	"mera mata",
	"mero",
	"mero mero",
	"metate",
	"meter a alguien al bote",
	"meter la pata",
	"meter un madrazo",
	"metiche",
	"metiche",
	"metiche",
	"mezquino",
	"mientras menos burros, más olotes",
	"migra",
	"mijo",
	"mirolear",
	"mirruña",
	"mirujear",
	"mitote",
	"Mocasin",
	"mochada",
	"mocharse",
	"mochila",
	"mocoso",
	"mojado",
	"molacho",
	"mondongo",
	"monitos",
	"mordida",
	"moretón",
	"Morraya",
	"Morro",
	"mota",
	"mota",
	"moto",
	"motorolo",
	"movia",
	"movida",
	"movida",
	"movida chueca",
	"muchachón",
	"muerto de hambre",
	"muerto el ahijado, se acabó el compadrazgo",
	"Mugroso",
	"muino",
	"mujeron",
	"mujerón",
	"músico pagado toca mal son",
	"n'hombre",
	"Naa",
	"nacer cansado",
	"nachas",
	"naco",
	"naco",
	"naco",
	"Nailons",
	"nalgón",
	"nalgueada",
	"ñáñaras",
	"ñáñaras",
	"ñango",
	"ñango o ñengo",
	"naranjas",
	"narices bola",
	"nave",
	"nave",
	"nel",
	"nel / nel pastel",
	"nel pastel",
	"nerdo",
	"ñero",
	"ñero",
	"Neta",
	"neta",
	"ni a balazos",
	"ni jota",
	"ni madres",
	"ni muy muy, ni tan tan.",
	"ni picha ni cacha ni deja batear",
	"nieve",
	"niguas",
	"ningunear",
	"no acabársela",
	"no fumar a alguien",
	"no hallar la puerta",
	"no hay fijón",
	"no hay Pex",
	"No mames",
	"No mames",
	"No Manches",
	"No me vengas con que a chuchita la bolsearon",
	"no medirse",
	"no te creas",
	"no tener alguien ni (un) quinto, o quedarse alguien sin un quinto",
	"no tener madre",
	"nomás acuérdate",
	"ñoño",
	"nopal",
	"norteada",
	"norteado",
	"nortearse",
	"ojete",
	"olérselas",
	"olérselas",
	"On tablas",
	"onda (buena o mala)",
	"orale",
	"orinita vengo,",
	"orita",
	"Pa tus Tunaz",
	"Pa' que amarre",
	"pacha",
	"pachanga",
	"pachanga",
	"pachanguear",
	"pachichi",
	"pachón",
	"pachuco",
	"pachuco",
	"padre",
	"padre",
	"padre",
	"Padriuris",
	"paisa",
	"paisano",
	"pajarear",
	"pájaro nalgón",
	"palapa",
	"paliacate",
	"palomazo",
	"palomilla",
	"panbolear",
	"panchólares",
	"pandroso",
	"pánel",
	"panucho",
	"panzona",
	"papalote",
	"papar moscas",
	"Papear",
	"para las pulgas",
	"paracaidista",
	"paracaidista",
	"parecer alguien ajolote.",
	"parecer árbol de navidad",
	"paro",
	"Parto sin dolor",
	"Pary, reve",
	"pasante",
	"pasar",
	"pasar bascula",
	"pasarse de lanza",
	"pata de perro",
	"Patas, pieseses",
	"patín",
	"patinerle el coco",
	"patrasear - de pa'trás",
	"Pecsi",
	"peda",
	"Pedalear tu Bicicleta",
	"pedinche",
	"pedir para las aguas.",
	"pedo",
	"Pedo",
	"pedo",
	"pedorriento",
	"pegar un llegue",
	"pegoste",
	"pegosteoso",
	"pegue",
	"pegue",
	"pejelagarto",
	"peladez",
	"pelado",
	"pelar",
	"pelar gallo",
	"pelo chino",
	"pelo parado",
	"pelos",
	"pelos de elote",
	"pendejada",
	"pendejo",
	"penoso",
	"pensión",
	"peor es nada",
	"pepenador",
	"pepenar",
	"perar",
	"perreado",
	"perrear",
	"perro",
	"perron",
	"persinado",
	"pertañar",
	"pesera o pesero",
	"pestañita",
	"pesudo",
	"petacas",
	"petacón",
	"petatearse",
	"pex",
	"pez",
	"picadero",
	"picap",
	"picarle",
	"picarse",
	"pichar",
	"pichicatear",
	"pichicatería",
	"pichicato",
	"pichurriento",
	"Picsa",
	"piernas de chichicuilote",
	"piernas de popote",
	"piernón",
	"piernudo",
	"pilón",
	"pinche",
	"pingas",
	"pingo",
	"Pintor de brocha gorda",
	"piocha",
	"piojo",
	"pípiris nais",
	"piruja",
	"pirujear",
	"pirujo",
	"pistear",
	"pisto",
	"pito",
	"plebe",
	"plomazo",
	"poca madre",
	"pochismo",
	"pocho",
	"poco a poco se le saca el agua al coco",
	"pollero",
	"pompas",
	"ponchado",
	"ponchar o checar tarjeta",
	"poner como camote",
	"poner el dedo",
	"poner los cuernos",
	"poner pinto",
	"poner un cuatro",
	"ponerse al brinco",
	"ponerse buzo",
	"ponerse color de hormiga",
	"ponerse con sus moños",
	"ponerse pedo",
	"ponerse pesado",
	"popis",
	"popó",
	"popote",
	"por ahí de",
	"pos",
	"prendérsele el foco",
	"prendido",
	"pringa",
	"pringado",
	"pringar",
	"pulmón",
	"puñal",
	"punta",
	"putazo",
	"putear",
	"putiza",
	"quebrarse la cabeza",
	"quedada",
	"quedar bien con alguien",
	"quedarse con las ganas",
	"quedarse de a seis",
	"quedarse para vestir santos",
	"quemacocos",
	"quemado",
	"quemar llanta",
	"quemarse",
	"quemarse las habas",
	"quemarse las pestañas",
	"quemón",
	"querendón",
	"rabo verde",
	"rajarse",
	"rajón",
	"ranchero",
	"rascada",
	"rascuacho",
	"raspa",
	"raspa",
	"rasquera",
	"raza",
	"recado",
	"recalentado",
	"recaudo",
	"recortar",
	"refinar",
	"refri",
	"refrito",
	"regar el tepache",
	"regazón",
	"rejego",
	"relajo",
	"relamido",
	"repatear",
	"repelar",
	"repelón",
	"resbaladilla",
	"resbalosa",
	"resistol",
	"retacha",
	"retache",
	"reven",
	"reventado",
	"reventón",
	"rifarse",
	"rola",
	"rolar",
	"rollero",
	"rollo",
	"ruco",
	"saber feo",
	"sabritas",
	"sacar canas verdes",
	"sacar de onda",
	"sacar el animal a tomar agua,",
	"sacar los trapitos al sol",
	"sacar un pedo",
	"sacarle",
	"sacatón o zacatón",
	"sale y vale",
	"sana, sana, colita de rana",
	"sangre de atole",
	"sangrón",
	"sarape",
	"se lo llevó phifas",
	"se me aflojo el mastique",
	"sentirse o creerse muy salsa.",
	"ser cajeta",
	"ser maleta",
	"ser un estuche de monerías",
	"servilleta",
	"sesera",
	"simón",
	"Simona la cacariza, simondon, yesca, sifilis wit gonorrea   Si",
	"sociales de los pobres",
	"suadero",
	"suato",
	"suave",
	"sueños guajiros",
	"suéter",
	"surfo",
	"surtirse",
	"ta cañón",
	"tabiro, tabaco, pitillo, cancerito",
	"tablas",
	"tachuela",
	"taco al pastor",
	"taco de cáncer",
	"taco de ojo",
	"tacos",
	"tacuche",
	"taja lápiz",
	"talabartería",
	"talacha",
	"talacha o talache o talacho",
	"talonear",
	"tamarindo",
	"tambache",
	"tambo",
	"tanto peca el que mata la vaca como el que le agarra la pata",
	"tanto pedo pa' cagar aguado",
	"tartamuda",
	"tarugada",
	"tarugo",
	"tatachas",
	"taxi de sitio",
	"te estoy dieciocho, pero no me quince",
	"tecolote",
	"tehuacán",
	"teip",
	"tembeleque",
	"tener a alguien hasta el gorro",
	"tepache",
	"teporocho",
	"tianguis",
	"tijera",
	"tiliche",
	"tilico",
	"tira-pari",
	"tirar a Lucas",
	"tirar el calzon",
	"tirar el rol",
	"titipuchal",
	"tizo",
	"tlapaleria",
	"tocho morocho",
	"tons que?",
	"torta",
	"tortillera",
	"totopo",
	"tracalero",
	"traer la llanta baja",
	"traer ponchada una llanta",
	"tragaaños",
	"trancazo",
	"tranquiza",
	"transa o tranza",
	"tribilín",
	"trinquetear",
	"tripear",
	"triques",
	"troca",
	"trola",
	"trompabulario",
	"trompudo",
	"tronar",
	"tronársela",
	"trono",
	"trucha",
	"trusa",
	"tumbaburros",
	"tumbado del burro",
	"tuna",
	"turistear",
	"turulo o turulato",
	"tusar",
	"un chingo",
	"un chorro",
	"un monton",
	"uñas largas",
	"uta, mano!",
	"vaciado",
	"vagaciones",
	"valedor",
	"valemadrista",
	"valer cacahuate",
	"valer gorro",
	"valer madre",
	"valió Calabaza",
	"vato",
	"velorio",
	"venganza de Moctezuma",
	"venir guango",
	"ver (la) cara de semilla",
	"verdá de Dios",
	"vetarro",
	"víbora",
	"vieja",
	"viejada",
	"vivito y coleando",
	"volado",
	"volteado",
	"voy a mi arbolito",
	"voy a tirar el miedo",
	"wachar",
	"y a ti ¿qué te arde?",
	"ya alcanza el timbre",
	"ya estufas",
	"ya mero",
	"ya ni pepsi",
	"yonque",
	"zacahuil",
	"zacate",
	"zacate de aqui",
	"zafado",
	"zopilote",
	"zorrear",
	"zotaco"])
;