application: sauci-catalog
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on
- deferred: on

handlers:
- url: /client/modules/(app|admin)/(build|release)/(.*/?.*\.(css|js|png|jpg|jpeg|tif|gif|woff|ttf|svg|json|map|eot|txt))
  static_files: client/modules/\1/\2/\3
  upload: client/modules/(app|admin)/(build|release)/(.*/?.*\.(css|js|png|jpg|jpeg|tif|gif|woff|ttf|svg|json|map|eot|txt))

- url: /client/manage/assets
  static_dir: client/manage/assets

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "latest"
- name: jinja2
  version: "latest"
- name: PIL
  version: "latest"
